---
title: "Colony level analyses"
output: html_document
date: "2026-03-16"
---

```{r}
library(tidyverse)
library(here)
library(dplyr)
library(readxl)
library(lmerTest)
library(emmeans)
library(broom)
library(lme4)
library(car)
library(corrplot)
library(Hmisc )
rm(list = ls())

#calculating ED50 for all datasets and combining with metadata
#read in metadata
file_path <-here("Data")
  cbass_metadata<-read_xlsx("Data/ESA_CBASS_metadata.xlsx")

EDsdf<-read.csv("Data/EDsdf-all.csv")
#read in all site files
files <- list.files(here("Data"), pattern = "PAM\\.csv$", full.names = TRUE)



#read in MAPP cluster df and fix sample ID names/cols
bloop_cluster<- read.csv("Data/expt_data_clustered.csv")
bloop_cluster <- bloop_cluster %>%
  mutate(
    clean = SampleID_clean %>%
      tolower() %>%
      sub("^t", "", .),   # remove leading "t"
    
    site = sub("_.*", "", clean),
    species = sub(".*_([a-z]+)[0-9]+$", "\\1", clean),
    genotype = sub(".*_([a-z]+)([0-9]+)$", "\\2", clean),
    
    GroupingProperty = paste(site, toupper(species), genotype, sep = "_")
  ) %>%
  select(-clean)
  

#combine cbass data
combined_df <- files %>%
  map_dfr(~ read_csv(.x) %>% mutate(source_file = basename(.x)))

#join metadata with raw pam value data to get grouping property into metadata
combined_df <- combined_df %>%
  left_join(cbass_metadata, by = c("Bag_number", "Species", "Site"))

combined_df <- combined_df %>%
  mutate(GroupingProperty = paste(Site, Species, Genotype, sep = "_"))


#remove duplicates 
metadata_small <- combined_df %>%
  mutate(Grouping_property = paste(Site, Species, Genotype, sep = "_")) %>%
  distinct(Grouping_property, .keep_all = TRUE)

EDsdf_clean <- EDsdf %>%
  select(-Species, -Site)  # drop duplicates if present

#combine 
cbass_dataset <- metadata_small %>%
  left_join(EDsdf_clean, by = "GroupingProperty") %>%

  left_join(bloop_cluster, by = "GroupingProperty")


cbass_dataset$DW <- cbass_dataset$ED95 - cbass_dataset$ED5
#clean
cbass_dataset <-  cbass_dataset %>% 
  select(
    GroupingProperty, 
    Species,
    Site,
    Tank_color, 
    Size_cm, 
    Partial_mortality,
    Colony_depth_ft, 
    ED50, 
    ED5, 
    ED95, 
    DW,
    Cluster_4,
    Cluster_5,
    Cluster_6,
    Cluster_7,
    Cluster_8)

write.csv(cbass_dataset, file = "Data/full_cbass_dataset.csv")

#long format
ED_long <- cbass_dataset %>%
  pivot_longer(
    cols = c(ED5, ED50, ED95, DW),
    names_to = "ED_level",
    values_to = "ED_value"
  ) %>%
  mutate(Species = factor(Species, levels = c("AABR", "AHYA", "AGLO", "ICRA")))

#subset each value
ED50 <- ED_long %>% filter(ED_level == "ED50")
ED5<- ED_long %>% filter(ED_level == "ED5")
ED95<- ED_long %>% filter(ED_level == "ED95")
DW<- ED_long %>% filter(ED_level == "DW")

#subset ICRA
ICRA<- ED_long %>% filter(Species == "ICRA")
  AGLO<- ED_long %>% filter(Species == "AGLO")
  AABR<- ED_long %>% filter(Species == "AABR")
  AHYA<- ED_long %>% filter(Species == "AHYA")
```

```{r}
#make phenotype plot
#removing sus samples that the cluster analysis show are likely mos-labeled (6 samples total)
  to_remove <- c("3_AGLO_3", "4_AGLO_7", "9_AABR_1", "11_ICRA_8", "11_ICRA_5", "11_ICRA_10")
df_clean <- ED_long %>% filter(!GroupingProperty %in% to_remove)

df_clean %>%
  filter(ED_level == "ED95") %>%
  mutate(Cluster_5 = as.factor(Cluster_5)) %>%
  ggplot(aes(x = Cluster_5, y = ED_value, fill = Cluster_5)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.7) +
  geom_jitter(width = 0.15, alpha = 0.6, size = 2) +
  facet_wrap(~Species, scales = "free_y") +
  theme_bw() +
  labs(
    x = "Phenotype Cluster",
    y = "ED5",
    title = "ED5 variation among phenotype clusters within species"
  )
```


```{r}
#visualize patterns across all taxa

#just change DW, ED95, etc here and plot
plot_df <- DW %>%
  pivot_longer(cols = c(Colony_depth_ft, Partial_mortality, Size_cm),
               names_to = "Predictor",
               values_to = "Value")

ggplot(plot_df,
       aes(x = Value, y = ED_value, color = Species)) +
  geom_point(alpha = 0.7) +
  geom_smooth(method = "lm", se = FALSE) +
    facet_grid(ED_level ~ Predictor, scales = "free") 

```
```{r}
#test collinearity 
 #make a correlation matrix
dat_wide <- ED_long %>%
  select(GroupingProperty, Size_cm, Partial_mortality,
         Colony_depth_ft, ED_level, ED_value, Cluster_5) %>%
  pivot_wider(names_from = ED_level, values_from = ED_value)

vars <- dat_wide %>%
  select(Size_cm,
         Partial_mortality,
         Colony_depth_ft,
         DW,
         ED5,
         ED50,
         ED95,
         Cluster_5) %>%
  mutate(across(everything(), as.numeric)) %>%
  na.omit()

res1 <- rcorr(as.matrix(vars), type = "pearson")

corrplot(
  res1$r,
  p.mat = res1$P,
  sig.level = 0.05,
  insig = "p-value",
  order = "hclust",
  addrect = 2,
  tl.srt = 45,
  tl.cex = 0.6,
  pch.cex = 0.8,
  type = "upper",
  method = "color",
  addCoef.col = "black"
)

 res1 <- rcorr(as.matrix(vars), type = "pearson")
 
 corrplot(cor_mat,    p.mat = res1$P,
         sig.level = 0.05, 
        sig = "p-value",
         order = 'hclust', 
         addrect = 2, 
         tl.srt = 45, 
         tl.cex = 0.6,  
         pch.cex = 0.8, 
         type = 'upper')
dev.off()
```

```{r}

#subset by spp to look at PM
plot_icra <- ICRA %>%
  pivot_longer(
    cols = c(Size_cm, Partial_mortality, Colony_depth_ft, Cluster_4),
    names_to = "Predictor",
    values_to = "Value"
  )
ggplot(plot_icra,
       aes(x = Value, y = ED_value)) +
  geom_point(alpha = 0.7) +
  geom_smooth(aes(group = 1), method = "lm", se = FALSE, color = "black") +
  facet_wrap(ED_level ~ Predictor, scales = "free") +
  theme_classic()

plot_aglo <- AGLO %>%
  pivot_longer(
    cols = c(Size_cm, Partial_mortality, Colony_depth_ft, Cluster_4),
    names_to = "Predictor",
    values_to = "Value"
  )
ggplot(plot_aglo,
       aes(x = Value, y = ED_value)) +
  geom_point(alpha = 0.7) +
  geom_smooth(aes(group = 1), method = "lm", se = FALSE, color = "black") +
  facet_wrap(ED_level ~ Predictor, scales = "free") +
  theme_classic()


#subset icra to look at PM

```


```{r}
#remember, Site effects are confounded with experimental runs and are therefore interpreted as block effects!!
#starting with grouped ED_values

#Q: Do colony traits affect ED, and do those effects differ among species? By using the split(ED_long, ED_long$ED_level), can test effect of each ED level.
models_main <- lapply(split(ED_long, ED_long$ED_level), function(df) {
  lmer(
    ED_value ~ Species + Colony_depth_ft + Partial_mortality + Size_cm + (1 | Site),
    data = df
  )
})


#add interactions (does xxx affect ED differently in each species)

models_int <- lapply(split(ED_long, ED_long$ED_level), function(df) {
  lmer(
    ED_value ~ Species * (Colony_depth_ft + Partial_mortality + Size_cm) + (1 | Site),
    data = df
  )
})


#compare models
anova_table <- lapply(names(models_main), function(ed) {
  m1 <- models_main[[ed]]
  m2 <- models_int[[ed]]
  
  an <- anova(m1, m2)
  
  an_df <- as.data.frame(an) %>%
    rownames_to_column("model") %>%
    mutate(ED_level = ed)
  
  an_df
}) %>%
  bind_rows()

anova_table

#model 1 show lower aic vals for each ED_level. no strong support for interactions




#extract
anova_main <- lapply(names(models_main), function(ed) {
  m <- models_main[[ed]]
  
  an <- anova(m)
  
  an_df <- as.data.frame(an) %>%
    rownames_to_column("term") %>%
    mutate(ED_level = ed)
  
  an_df
}) %>%
  bind_rows()

anova_main


#emmeans
emmeans_table <- lapply(names(models_main), function(ed) {
  m <- models_main[[ed]]
  
  em <- emmeans(m, pairwise ~ Species)
  
  tidy(em$contrasts) %>%
    mutate(ED_level = ed)
}) %>%
  bind_rows()

emmeans_table
```


```{r}
#individual trait effects

#depth
depth_table <- lapply(names(models_main), function(ed) {
  m <- models_main[[ed]]
  
  em <- emtrends(m, ~ Species, var = "Colony_depth_ft")
  
  tidy(em) %>%
    mutate(ED_level = ed, predictor = "Depth")
}) %>%
  bind_rows()

#PM
pm_table <- lapply(names(models_main), function(ed) {
  m <- models_main[[ed]]
  
  em <- emtrends(m, ~ Species, var = "Partial_mortality")
  
  tidy(em) %>%
    mutate(ED_level = ed, predictor = "PM")
}) %>%
  bind_rows()

#size
size_table <- lapply(names(models_main), function(ed) {
  m <- models_main[[ed]]
  
  em <- emtrends(m, ~ Species, var = "Size_cm")
  
  tidy(em) %>%
    mutate(ED_level = ed, predictor = "Size")
}) %>%
  bind_rows()

trait_effects <- bind_rows(depth_table, pm_table, size_table)

trait_effects


```

```{r}
#combined traits
lmm_traits_combined <- lmer(
  ED_value ~ Species * ED_level +
    Colony_depth_ft + Partial_mortality + Size_cm +
    (1 | Site),
  data = ED_long
)

anova(lmm_traits_combined)
#ED_level is sig
```
```{r}
ED_long$Cluster_4 <- as.factor(ED_long$Cluster_4 )
ED_long$Cluster_5 <- as.factor(ED_long$Cluster_5 )
ED_long$Cluster_6 <- as.factor(ED_long$Cluster_6 )
ED_long$Cluster_7 <- as.factor(ED_long$Cluster_7 )
ED_long$Cluster_8 <- as.factor(ED_long$Cluster_8 )

```

```{r}
#For ICRA only. Do colony size or partial mortality predict ED values after accounting for site-level variation?
 # ED_long %>%
 #     ggplot(aes(x = Cluster_4, y = ED_value, color = Species)) +
 #     geom_point(size = 2, alpha = 0.7) +
 #     geom_smooth(method = "lm", se = TRUE) +
 #     facet_wrap(~ED_level, scales = "free_y") +
 #     theme_bw()

 ICRA %>%
     ggplot(aes(x = Partial_mortality, y = ED_value, color = Species)) +
     geom_point(size = 2, alpha = 0.7) +
     geom_smooth(method = "lm", se = TRUE) +
     facet_wrap(~ED_level, scales = "free_y") +
     theme_bw()
 
#test if PM and size are collinear
ggplot(ICRA, aes(Size_cm, Partial_mortality)) +
  geom_point(alpha = 0.7) +
  geom_smooth(method = "lm", se = TRUE) +
  theme_bw()
 cor.test(ICRA$Size_cm, ICRA$Partial_mortality, method = "pearson")
 cor.test(ICRA$Size_cm, ICRA$Partial_mortality, method = "spearman")

 #make a correlation matrix
 ICRA_wide <- ICRA %>%
  select(GroupingProperty, Size_cm, Partial_mortality,
         Colony_depth_ft, ED_level, ED_value, Cluster_5) %>%
  pivot_wider(names_from = ED_level, values_from = ED_value)
 
 cor_mat <- ICRA_wide %>%
  select(Size_cm, Partial_mortality, Colony_depth_ft, DW, ED5, ED50, ED95, Cluster_5) %>%
  cor(use = "pairwise.complete.obs", method = "pearson")
 
 corrplot(cor_mat, method = "color", type = "upper",
         addCoef.col = "black", tl.cex = 0.7)
 
 vars <- ICRA_wide %>%
  select(Size_cm,
         Partial_mortality,
         Colony_depth_ft,
         DW,
         ED5,
         ED50,
         ED95,
         Cluster_5) %>%
  mutate(across(everything(), as.numeric)) %>%
  na.omit()
 
 res1 <- rcorr(as.matrix(vars), type = "pearson")
 
 corrplot(cor_mat,  p.mat = res1$P,
         sig.level = 0.05, 
         sig = "p-value",
         order = 'hclust', 
         addrect = 2, 
         tl.srt = 45, 
         tl.cex = 0.6,  
         pch.cex = 0.8, 
         type = 'upper')
dev.off()
 
#run seeprate model for each ED
#linear model
lm_model_icra <- lapply(split(ICRA, ICRA$ED_level), function(df) {
lm(
 ED_value ~ Partial_mortality + Size_cm + Site,
 data=df
)})
lapply(lm_model_icra, anova)

#linear mixed effects model
models_icra <- lapply(split(ICRA, ICRA$ED_level), function(df) {
  lmer(
    ED_value ~ Partial_mortality + Size_cm + (1 | Site),
    data = df
  )
})

lapply(models_icra, Anova, type = 2)


#across ed level
lmer(
 ED_value ~ ED_level + Size_cm + Partial_mortality +
 (1|Site) + (1|GroupingProperty),
 data = ICRA
)

```

```{r}
ICRA$Cluster_4 <- as.factor(ICRA$Cluster_4)
ICRA$Cluster_5 <- as.factor(ICRA$Cluster_5)
ICRA$Cluster_6 <- as.factor(ICRA$Cluster_6)
ICRA$Cluster_7 <- as.factor(ICRA$Cluster_7)
ICRA$Cluster_8 <- as.factor(ICRA$Cluster_8)

 m4 <- lm(ED_value ~ ED_level + Cluster_4, data=ICRA)
m5 <- lm(ED_value ~ ED_level + Cluster_5, data=ICRA)
m6 <- lm(ED_value ~ ED_level + Cluster_6, data=ICRA)
m7 <- lm(ED_value ~ ED_level + Cluster_7, data=ICRA)
m8 <- lm(ED_value ~ ED_level + Cluster_8, data=ICRA)
AIC(m4,m5,m6, m7, m8)
#models 4 and 5 are tied


anova(m4)

emmans 


anova(m5)


```

